#!/bin/bash

bash /usr/local/taiga/configure

cd /usr/local/taiga/taiga-back/

python manage.py collectstatic --noinput

echo "Waiting for Postgresql to be available..."
while ! nc -z $POSTGRES_PORT_5432_TCP_ADDR 5432; do
  sleep 1
done

pip install --upgrade -r requirements.txt
python manage.py migrate --noinput
python manage.py compilemessages
python manage.py collectstatic --noinput
python manage.py migrate taiga_contrib_slack
if [ ! -e /usr/local/taiga/logs/initial_setup_done ]; then
  python manage.py loaddata initial_user
  python manage.py loaddata initial_project_templates
  python manage.py loaddata initial_role
  python manage.py compilemessages
  python manage.py collectstatic --noinput
  chown -R taiga:taiga /usr/local/taiga
  touch /usr/local/taiga/logs/initial_setup_done
fi

/usr/local/bin/circusd /usr/local/taiga/circus.ini
